name: Metrics
on:
  schedule: [{ cron: "0 8 * * *" }] # Everyday at 08h00 UTC
  workflow_dispatch: # allow to launch it manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories
          plugin_languages: yes
          plugin_achievements: yes
